apiVersion: apps/v1
kind: Deployment #kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: aymen065/locationback
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090 #port de conteneur

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8090 #port de service
      targetPort: 8090 #port exposé par le service
  type: NodePort #type de service